### ISSUE TITLE
Feature: par_lapply, par_apply, foreach

### ISSUE THREAD

**Issue by Hallo951** [mihaiconstantin/parabar#30]
Hi,

it would be wonderful if you could add the functionalities for lapply, apply and foreach....

best Frank

**Comment by mihaiconstantin** [comment]
Thanks for the suggestion. Adding parallel implementations for `lapply` and `apply` is high on my list. About `foreach`, I am still considering. I will keep this issue open for reference.

**Comment by mihaiconstantin** [comment]
See #31 for `par_lapply` support. The `par_apply` is also coming soon.

**Comment by mihaiconstantin** [comment]
Also, see #36 for `par_apply` support.

**Comment by mihaiconstantin** [comment]
I am closing this issue as completed. I am not convinced about adding support for `foreach` at this moment. In general, I aim to limit the number of dependencies and stay as close as possible to what ships with `R`. That being said:
- I might consider it in the future if you can make a good case for it.
- Another option is to have a separate package that extends `parabar` with a `foreach` backend (e.g., see [design here](https://raw.githubusercontent.com/mihaiconstantin/parabar/main/inst/design/parabar-design.drawio.svg)).

**Comment by mihaiconstantin** [comment]
See #53 for how `parabar` can be used with `foreach`.
